version: '3.7'

services:
  ms-sample:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: ms-sample
    depends_on:
      - ms-sample-mongo
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  ms-sample-mongo:
    image: mongo:latest
    container_name: ms-sample-mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - db-ms-sample-volume:/data/db


volumes:
  db-ms-sample-volume: