version: "3.7"

services:
  # ---> MS-Sample-Server <---
  project:
    build:
      context: ../
      dockerfile: ./.docker/node.dockerfile
    image: ms-sample-project
    container_name: ms-sample-project
    restart: unless-stopped
    working_dir: /usr/src
    env_file: ../.env
    ports:
      - ${SERVER_PORT}:4000
    volumes:
      - project-log-volume:/usr/src/services
    networks:
      - ms-sample-network
    stdin_open: true
    tty: true

  # ---> MS-Sample-Database <---
  ms-sample-mongo:
    image: mongo:latest
    container_name: ms-sample-mongo
    # env_file:
    #   - .env
    # environment:
    #   DB_PASS: ${DB_PASS}
    #   DB_USER: ${DB_USER}
    restart: always
    networks:
      - ms-sample-network
    ports:
      - ${DB_PORT}:27017
    volumes:
      - db-ms-sample-volume:/data/db

  # ---> MS-Sample-REDIS <---
  # ms-sample-redis:
  #   container_name: ms-sample-redis
  #   image: "bitnami/redis:latest"
  #   user: "root"
  #   environment:
  #     ALLOW_EMPTY_PASSWORD: "yes"
  #   networks:
  #     - ms-sample-network
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   restart: unless-stopped
  #   volumes:
  #     - ${REDIS_PASS}/ms-sample-redis:/bitnami/redis

networks:
  ms-sample-network:
    external:
      name: ms-sample-network

volumes:
  project-log-volume:
