version: "3.7"

services:
  # --------> API-Server <--------
  api-app:
    build:
      context: ../
      dockerfile: ./.docker/node.dockerfile
    image: api-app
    container_name: api-app
    restart: unless-stopped
    working_dir: /usr/src
    env_file: ../.env
    ports:
      - 4000:4000
    volumes:
      - api-app-volume:/usr
    networks:
      - my-network
    stdin_open: true
    tty: true


  # --------> MY-APP-MONGODB <--------
  mongo-app:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
    ports:
      - 27017:27017
    volumes:
      - /data/db2:/data/db
    networks:
      - my-network

  # --------> MY-APP-MYSQL <--------
  # my-mysql:
  #   image: mysql:latest
  #   container_name: my-mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes:
  #     - my-mysql-volume:/var/lib/mysql
  #   networks:
  #     - my-network
  #   env_file:
  #     - .env
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASS}


  # --------> MY-APP-REDIS <--------
  # my-redis:
  #   container_name: my-redis
  #   image: "bitnami/redis:latest"
  #   user: "root"
  #   environment:
  #     ALLOW_EMPTY_PASSWORD: "yes"
  #   networks:
  #     - my-network
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   restart: unless-stopped
  #   volumes:
  #     - ${REDIS_PASS}/my-redis:/bitnami/redis

networks:
  my-network:
    external:
      name: my-network

volumes:
  api-app-volume:
  my-mongodb-volume:
  # my-mysql-volume:
